/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns/$slug'
import { Route as InteractiveCampaignsIndexRouteImport } from './routes/interactive-campaigns/index'
import { Route as InteractiveCampaignsCampaignRouteImport } from './routes/interactive-campaigns/$campaign'
import { Route as CampaignsSlugIndexRouteImport } from './routes/campaigns/$slug/index'
import { Route as CampaignsSlugActivityRouteImport } from './routes/campaigns/$slug/activity'
import { Route as CampaignsSlugCodeRouteImport } from './routes/campaigns/$slug/code'
import { Route as CampaignsSlugKycRouteImport } from './routes/campaigns/$slug/kyc'
import { Route as CampaignsSlugRequirementRouteImport } from './routes/campaigns/$slug/requirement'
import { Route as CampaignsSlugResultRouteImport } from './routes/campaigns/$slug/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveCampaignsIndexRoute =
  InteractiveCampaignsIndexRouteImport.update({
    id: '/interactive-campaigns/',
    path: '/interactive-campaigns/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InteractiveCampaignsCampaignRoute =
  InteractiveCampaignsCampaignRouteImport.update({
    id: '/interactive-campaigns/$campaign',
    path: '/interactive-campaigns/$campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsSlugIndexRoute = CampaignsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugActivityRoute = CampaignsSlugActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugCodeRoute = CampaignsSlugCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugKycRoute = CampaignsSlugKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => CampaignsSlugRoute,
} as any)
const CampaignsSlugRequirementRoute =
  CampaignsSlugRequirementRouteImport.update({
    id: '/requirement',
    path: '/requirement',
    getParentRoute: () => CampaignsSlugRoute,
  } as any)
const CampaignsSlugResultRoute = CampaignsSlugResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => CampaignsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contacts': typeof ContactsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/interactive-campaigns/$campaign': typeof InteractiveCampaignsCampaignRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/interactive-campaigns/': typeof InteractiveCampaignsIndexRoute
  '/campaigns/$slug/activity': typeof CampaignsSlugActivityRoute
  '/campaigns/$slug/code': typeof CampaignsSlugCodeRoute
  '/campaigns/$slug/kyc': typeof CampaignsSlugKycRoute
  '/campaigns/$slug/requirement': typeof CampaignsSlugRequirementRoute
  '/campaigns/$slug/result': typeof CampaignsSlugResultRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contacts': typeof ContactsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/interactive-campaigns/$campaign': typeof InteractiveCampaignsCampaignRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/interactive-campaigns': typeof InteractiveCampaignsIndexRoute
  '/campaigns/$slug/activity': typeof CampaignsSlugActivityRoute
  '/campaigns/$slug/code': typeof CampaignsSlugCodeRoute
  '/campaigns/$slug/kyc': typeof CampaignsSlugKycRoute
  '/campaigns/$slug/requirement': typeof CampaignsSlugRequirementRoute
  '/campaigns/$slug/result': typeof CampaignsSlugResultRoute
  '/campaigns/$slug': typeof CampaignsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contacts': typeof ContactsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/use-cases': typeof UseCasesRoute
  '/campaigns/$slug': typeof CampaignsSlugRouteWithChildren
  '/interactive-campaigns/$campaign': typeof InteractiveCampaignsCampaignRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/interactive-campaigns/': typeof InteractiveCampaignsIndexRoute
  '/campaigns/$slug/activity': typeof CampaignsSlugActivityRoute
  '/campaigns/$slug/code': typeof CampaignsSlugCodeRoute
  '/campaigns/$slug/kyc': typeof CampaignsSlugKycRoute
  '/campaigns/$slug/requirement': typeof CampaignsSlugRequirementRoute
  '/campaigns/$slug/result': typeof CampaignsSlugResultRoute
  '/campaigns/$slug/': typeof CampaignsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/contacts'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/use-cases'
    | '/campaigns/$slug'
    | '/interactive-campaigns/$campaign'
    | '/campaigns/'
    | '/interactive-campaigns/'
    | '/campaigns/$slug/activity'
    | '/campaigns/$slug/code'
    | '/campaigns/$slug/kyc'
    | '/campaigns/$slug/requirement'
    | '/campaigns/$slug/result'
    | '/campaigns/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/contacts'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/use-cases'
    | '/interactive-campaigns/$campaign'
    | '/campaigns'
    | '/interactive-campaigns'
    | '/campaigns/$slug/activity'
    | '/campaigns/$slug/code'
    | '/campaigns/$slug/kyc'
    | '/campaigns/$slug/requirement'
    | '/campaigns/$slug/result'
    | '/campaigns/$slug'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/contacts'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/use-cases'
    | '/campaigns/$slug'
    | '/interactive-campaigns/$campaign'
    | '/campaigns/'
    | '/interactive-campaigns/'
    | '/campaigns/$slug/activity'
    | '/campaigns/$slug/code'
    | '/campaigns/$slug/kyc'
    | '/campaigns/$slug/requirement'
    | '/campaigns/$slug/result'
    | '/campaigns/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactsRoute: typeof ContactsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UseCasesRoute: typeof UseCasesRoute
  CampaignsSlugRoute: typeof CampaignsSlugRouteWithChildren
  InteractiveCampaignsCampaignRoute: typeof InteractiveCampaignsCampaignRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  InteractiveCampaignsIndexRoute: typeof InteractiveCampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-campaigns/': {
      id: '/interactive-campaigns/'
      path: '/interactive-campaigns'
      fullPath: '/interactive-campaigns/'
      preLoaderRoute: typeof InteractiveCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-campaigns/$campaign': {
      id: '/interactive-campaigns/$campaign'
      path: '/interactive-campaigns/$campaign'
      fullPath: '/interactive-campaigns/$campaign'
      preLoaderRoute: typeof InteractiveCampaignsCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug/': {
      id: '/campaigns/$slug/'
      path: '/'
      fullPath: '/campaigns/$slug/'
      preLoaderRoute: typeof CampaignsSlugIndexRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/activity': {
      id: '/campaigns/$slug/activity'
      path: '/activity'
      fullPath: '/campaigns/$slug/activity'
      preLoaderRoute: typeof CampaignsSlugActivityRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/code': {
      id: '/campaigns/$slug/code'
      path: '/code'
      fullPath: '/campaigns/$slug/code'
      preLoaderRoute: typeof CampaignsSlugCodeRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/kyc': {
      id: '/campaigns/$slug/kyc'
      path: '/kyc'
      fullPath: '/campaigns/$slug/kyc'
      preLoaderRoute: typeof CampaignsSlugKycRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/requirement': {
      id: '/campaigns/$slug/requirement'
      path: '/requirement'
      fullPath: '/campaigns/$slug/requirement'
      preLoaderRoute: typeof CampaignsSlugRequirementRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
    '/campaigns/$slug/result': {
      id: '/campaigns/$slug/result'
      path: '/result'
      fullPath: '/campaigns/$slug/result'
      preLoaderRoute: typeof CampaignsSlugResultRouteImport
      parentRoute: typeof CampaignsSlugRoute
    }
  }
}

interface CampaignsSlugRouteChildren {
  CampaignsSlugActivityRoute: typeof CampaignsSlugActivityRoute
  CampaignsSlugCodeRoute: typeof CampaignsSlugCodeRoute
  CampaignsSlugKycRoute: typeof CampaignsSlugKycRoute
  CampaignsSlugRequirementRoute: typeof CampaignsSlugRequirementRoute
  CampaignsSlugResultRoute: typeof CampaignsSlugResultRoute
  CampaignsSlugIndexRoute: typeof CampaignsSlugIndexRoute
}

const CampaignsSlugRouteChildren: CampaignsSlugRouteChildren = {
  CampaignsSlugActivityRoute: CampaignsSlugActivityRoute,
  CampaignsSlugCodeRoute: CampaignsSlugCodeRoute,
  CampaignsSlugKycRoute: CampaignsSlugKycRoute,
  CampaignsSlugRequirementRoute: CampaignsSlugRequirementRoute,
  CampaignsSlugResultRoute: CampaignsSlugResultRoute,
  CampaignsSlugIndexRoute: CampaignsSlugIndexRoute,
}

const CampaignsSlugRouteWithChildren = CampaignsSlugRoute._addFileChildren(
  CampaignsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactsRoute: ContactsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UseCasesRoute: UseCasesRoute,
  CampaignsSlugRoute: CampaignsSlugRouteWithChildren,
  InteractiveCampaignsCampaignRoute: InteractiveCampaignsCampaignRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  InteractiveCampaignsIndexRoute: InteractiveCampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
